security:
  oauth2:
    client:
      clientId: 1042261496185-4hjr48k61ek4115o4h4rfm9o4u3kiod1.apps.googleusercontent.com
      clientSecret: 8xRp5TsD924spnebz8-LYqKA
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/oauth2
#    username: admin
#    password: 123
#    driverClassName: com.mysql.jdbc.Driver
#    tomcat:
#      max-wait: 10000
#      max-active: 5
#      max-idle: 2
#      min-idle: 1
#  jpa:
#    show-sql: true
    
#hibernate:
#  dialect: org.hibernate.dialect.MySQL5Dialect
#  ddl-auto: create-drop
##none, validate, update or create-drop
  mvc: 
    view:
      prefix: /jsp/
      suffix: .jsp

logging:
  level:
    root: WARN
    org:
      springframework: DEBUG
    com:
      springboot: INFO    
      
  file: oauth2.log

server:
  port: 8080